### ISSUE TITLE
Requirements doc 3.5.2 and 3.5.2.3 are duplicates

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#2]
Look at this and remove duplication or fill in missing documentation.

**Comment by jviel** [comment]
I started making changes to the .docx file only to realize that I can't edit the table of contents. Nor can I save as docx; probably because I don't have Word. Here are the rewritten sections if someone else wants to do the edits then push:
"
3.5.2 Create, Update, or Remove Service
Managers alone shall have editing power over the Provider Directory, or list of services.
3.5.2.1 Create Service
Managers shall have the option to enter a Service’s name, six-digit code, and fee to place a new Service into the database. Managers shall also have the ability to re-activate a Service that has been Removed.
3.5.2.2 Update Service
Managers shall have access to a Service record to update the Service’s name or fee.
3.5.2.3 Remove Service
Managers shall have the ability to remove services from the Provider Directory when necessary.
"

**Comment by thuselem** [comment]
Documentation updated.
