### ISSUE TITLE
Consultation doesn't get added to the db from Terminal

### ISSUE THREAD

**Issue by evsiretanu** [Gilmore-PDX-CS/Group9#58]
when adding a consultation, you have `123456789` for provider ID and `123456`  (line 518) for consultation all the time, and `Database` returns `-2` but `if (db.addConsultation(consultation) >= 0)` (line 544) doesn't catch it for some reason

**Comment by jviel** [comment]
Working on this. I fixed Provider menu so that it will ask you for your provider id to login. This has to happen at some point bc adding a consultation requires a provider id anyway.
As for consultation number, that is arbitrary because the database assigns a unique value before adding to database anyway.

**Comment by jviel** [comment]
Also, on my end the consultation is being added to the db. Currently there is no way to check which transactions are in the database so maybe that's what you're seeing

**Comment by evsiretanu** [comment]
All consultations should be under `Transactions` and just have the same `consultID` for transactions from the same consultations. But no transactions get added to the `.db`

**Comment by evsiretanu** [comment]
It was not adding it because of wrong provider id
