### ISSUE TITLE
Database Exception in getAllServices()

### ISSUE THREAD

**Issue by andy-keene** [Gilmore-PDX-CS/Group9#95]
Each call to Database.getAllServices() is now throwing an exception. See attached pic.
<img width="469" alt="screen shot 2016-11-25 at 1 10 33 pm" src="https://cloud.githubusercontent.com/assets/20017363/20635343/dd3a8228-b310-11e6-8149-796f62ad9576.png">

**Comment by mbottini** [comment]
The problem is with the new validation that the Service class does, created in Pull Request #84. The relevant regex is `[a-zA-Z]+`, which invalidates the "Test 1" service names that I had in there.

In any case, I fixed the couple of invalid Services in the test database that cause the exception. Pull Request #96 addresses this. To prevent exceptions from popping up, run TestDB and replace the existing `database.db` with `TestDB.db`.

**Comment by andy-keene** [comment]
What was weird was this was happening only in my service print and not
Johnnys. Let's get this merged then I will retest

**Comment by andy-keene** [comment]
Good job Mike!
